[versions]
project = "1.0.0-alpha.2"
jackson = "2.9.0"
junit = "5.3.1"
cucumber = "6.10.4"
jpa = "2.2"
cucumberJunit = "5.1.1"
slf4j = "2.0.17"
javalin = "4.6.8"
mockserver = "5.11.2"
hibernate = "5.4.0.Final"
jacoco = "0.8.10"

[libraries]
prod-jsch = { module = "com.jcraft:jsch", version = "0.1.55" }
prod-snakeyaml = { module = "org.yaml:snakeyaml", version = "2.0" }
prod-javalite = { module = "org.javalite:javalite-common", version = "1.2.2" }
prod-jpa = { module = "javax.persistence:javax.persistence-api", version.ref = "jpa" }
prod-orika = { module = "ma.glasnost.orika:orika-core", version = "1.5.4" }
prod-reflections = { module = "org.reflections:reflections", version = "0.9.11" }
prod-cucumber = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
prod-jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
prod-jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
prod-javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
prod-tika-core = { module = "org.apache.tika:tika-core", version = "1.28.5" }
prod-selenium = { module = "org.seleniumhq.selenium:selenium-java", version = "3.141.59" }
prod-playwight = { module = "com.microsoft.playwright:playwright", version = "1.50.0" }
prod-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

test-junit = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
test-junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
test-junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
test-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.3.1" }
test-mockito-inline = { module = "org.mockito:mockito-inline", version = "4.0.0" }
test-assertj = { module = "org.assertj:assertj-core", version = "3.21.0" }
test-lombok = { module = "org.projectlombok:lombok", version = "1.18.4" }
test-zip4j = { module = "net.lingala.zip4j:zip4j", version = "2.10.0" }
test-awaitility = { module = "org.awaitility:awaitility", version = "3.0.0" }
test-h2 = { module = "com.h2database:h2", version = "1.4.200" }
test-hibernate = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }
test-hibernate-entitymanager = { module = "org.hibernate:hibernate-entitymanager", version.ref = "hibernate" }
test-jpa = { module = "javax.persistence:javax.persistence-api", version.ref = "jpa" }
test-guava = { module = "com.google.guava:guava", version = "20.0" }
test-mockserver = { module = "org.mock-server:mockserver", version.ref = "mockserver" }
test-mockserver-netty = { module = "org.mock-server:mockserver-netty", version.ref = "mockserver" }
test-commons-fileupload = { module = "commons-fileupload:commons-fileupload", version = "1.4" }
test-slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
test-slf4j-test = { module = "com.github.valfirst:slf4j-test", version = "3.0.0" }
test-cucumber = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
test-cucumber-junit = { module = "io.cucumber:cucumber-junit", version.ref = "cucumberJunit" }
test-cucumber-picocontainer = { module = "io.cucumber:cucumber-picocontainer", version.ref = "cucumberJunit" }
test-javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
test-pug4j = { module = "de.neuland-bfi:pug4j", version = "2.3.1" }
test-jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
#TODO remove
test-jsonassert = { module = "org.skyscreamer:jsonassert", version = "1.5.0" }

[plugins]
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }